### ISSUE TITLE
WSS tag is erroneously overlayed over image scrambled with Videocrypt

### ISSUE THREAD

**Issue by Zcooger** [fsphil/hacktv#45]
WSS tag is stationary.
Additionaly it is placed on wrong line since single line buffer is applied and in result it should land higher.
I bet aspect ratio switch is working until the video is scrambled. After decoding WSS tag may be displaced and messed by the decoder so I suggest to:
1. Overlay WSS tag first.
2. Scramble the image.

Command I used:
`hacktv -m pal -t uint8 -o ebu_vc.bin --videocrypt free --wss auto ebu75.avi`

![ebu_vc](https://user-images.githubusercontent.com/42012614/64849462-b6bbe280-d613-11e9-9004-c9df4055e2b6.png)

**Comment by fsphil** [comment]
No, this is the correct behaviour. Videocrypt decoders do not modify line 23.

**Comment by fsphil** [comment]
Normally videocrypt encoders will place the scrambled version of line 24 on line 23. hacktv doesn't do this in order to preserve the WSS signal. The result of this is that the WSS will actually appear twice in the descrambled output, an untouched version on line 23 and a 'descrambled' version on line 24.
